//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewsManager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Nouvelle
    {
        public int Id { get; set; }
        public string Titre { get; set; }
        public string Texte { get; set; }
        public string ImageUrl { get; set; }
        public System.DateTime DateAjout { get; set; }
        public int CategorieId { get; set; }
    
        public virtual Category Category { get; set; }
    }
}
